# Goal definition
geometry_msgs/Point target_position
float32 target_yaw
float32 position_tolerance
float32 yaw_tolerance
---
# Result definition
bool success
string message
---
# Feedback definition
float32 distance_to_goal